amcl:
  ros__parameters: {use_sim_time: true}

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1
      use_astar: false

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.22
      min_vel_theta: 0.0
      max_vel_theta: 2.84
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      vx_samples: 20
      vtheta_samples: 20

bt_navigator: {ros__parameters: {use_sim_time: true}}
behavior_server: {ros__parameters: {use_sim_time: true}}
waypoint_follower: {ros__parameters: {use_sim_time: true}}

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.14
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 0.5
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      robot_radius: 0.14
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer: {plugin: "nav2_costmap_2d::StaticLayer"}
      obstacle_layer: {plugin: "nav2_costmap_2d::ObstacleLayer"}
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.8
