slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox_params:
      resolution: 0.05
      max_laser_range: 3.5
      minimum_time_interval: 0.1
      map_update_interval: 1.0
      publish_period: 1.0
      mode: "mapping"
